import { db } from "../db";
import { sql } from "drizzle-orm";
import { storage } from "../storage";

export async function generateFounderWeeklyBrief() {
  const result = await db.execute(sql`
    select
      coalesce((select sum(amount_paid) from orders where status = 'paid'), 0)::int as revenue,
      coalesce((select avg(amount_paid) from orders where status = 'paid'), 0)::int as avg_order,
      coalesce((select count(*) from chat_conversations where lead_temperature = 'hot'), 0)::int as hot_leads,
      coalesce((select count(*) from orders where status = 'paid'), 0)::int as paid_orders,
      coalesce((select count(*) from chat_conversations where pipeline_stage = 'booked'), 0)::int as booked_sessions,
      coalesce((select count(*) from bookings where status = 'pending'), 0)::int as pending_bookings
  `);

  const metrics = result.rows[0] ?? {};

  const report = await storage.createDigestReportTyped({
    title: "Founder Weekly Brief",
    content: JSON.stringify(metrics),
    narrative: `Weekly brief generated automatically. Revenue: $${(Number((metrics as any).revenue ?? 0) / 100).toFixed(2)}, Hot leads: ${(metrics as any).hot_leads ?? 0}, Paid orders: ${(metrics as any).paid_orders ?? 0}.`,
    weekStart: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    weekEnd: new Date(),
    reportType: "founder_weekly_brief",
    periodStart: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    periodEnd: new Date(),
    meta: metrics as any,
    topIntents: [],
    hotLeadsCount: Number((metrics as any).hot_leads ?? 0),
    qualifiedCount: 0,
    bookedCount: Number((metrics as any).booked_sessions ?? 0),
    wonValue: Number((metrics as any).revenue ?? 0),
    followupsDue: 0,
    unansweredHotLeads: 0,
    knowledgeBackedChats: 0,
    conversionByIntent: {},
  });

  return {
    summary: "generated founder weekly brief",
    meta: { reportId: report.id },
  };
}

export async function generateMonthlyStrategyBrief() {
  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);

  const report = await storage.createDigestReportTyped({
    title: "Monthly Strategy Brief",
    content: "Monthly strategy brief generated by Phase 49 automation.",
    narrative: `Monthly strategy brief for ${now.toLocaleString("default", { month: "long" })} ${now.getFullYear()}.`,
    weekStart: monthStart,
    weekEnd: now,
    reportType: "monthly_strategy_brief",
    periodStart: monthStart,
    periodEnd: now,
    meta: {} as any,
    topIntents: [],
    hotLeadsCount: 0,
    qualifiedCount: 0,
    bookedCount: 0,
    wonValue: 0,
    followupsDue: 0,
    unansweredHotLeads: 0,
    knowledgeBackedChats: 0,
    conversionByIntent: {},
  });

  return {
    summary: "generated monthly strategy brief",
    meta: { reportId: report.id },
  };
}
