import { createContext, useContext, useState, type ReactNode } from "react";

export type Language = "en" | "fr" | "es" | "pt" | "zh" | "ja" | "ru" | "yo";

export const LANGUAGES: { code: Language; label: string; native: string }[] = [
  { code: "en", label: "English",    native: "EN" },
  { code: "fr", label: "Français",   native: "FR" },
  { code: "es", label: "Español",    native: "ES" },
  { code: "pt", label: "Português",  native: "PT" },
  { code: "zh", label: "中文",        native: "ZH" },
  { code: "ja", label: "日本語",      native: "JA" },
  { code: "ru", label: "Русский",    native: "RU" },
  { code: "yo", label: "Yorùbá",     native: "YO" },
];

const translations = {
  en: {
    nav_apps: "Apps",
    nav_books: "Books",
    nav_music: "Music",
    nav_art: "Art",
    nav_blog: "Blog",
    nav_contact: "Get in Touch",
    hero_badge: "Official Brand Portfolio",
    hero_headline_1: "Elevate Your World",
    hero_headline_2: "with Elevate360",
    hero_sub: "Apps · Books · Music · Art — one brand, infinite impact.",
    hero_cta_primary: "Explore Products",
    hero_cta_secondary: "Get in Touch",
    section_apps: "Mobile Applications",
    section_books: "Publications",
    section_music: "Music",
    section_art: "Art Studio",
    section_youtube: "Watch on YouTube",
    section_youtube_sub: "Exclusive content, product showcases, and creator insights on the Elevate360 YouTube channel.",
    section_compare: "Compare Our Books",
    section_compare_sub: "Find the right book for your journey — wellness, love, or healthy living.",
    footer_tagline: "Elevate the world, one product at a time.",
    cta_view_channel: "View Full Channel",
    cta_buy_amazon: "Buy on Amazon",
    cta_open_app: "Open App",
    cta_visit_etsy: "Visit Art Studio",
    cta_subscribe: "Subscribe — It's Free",
    press_kit: "Press Kit",
  },
  fr: {
    nav_apps: "Applications",
    nav_books: "Livres",
    nav_music: "Musique",
    nav_art: "Art",
    nav_blog: "Blog",
    nav_contact: "Contactez-nous",
    hero_badge: "Portefeuille de Marque Officiel",
    hero_headline_1: "Élevez Votre Monde",
    hero_headline_2: "avec Elevate360",
    hero_sub: "Applications · Livres · Musique · Art — une marque, un impact infini.",
    hero_cta_primary: "Explorer les Produits",
    hero_cta_secondary: "Contactez-nous",
    section_apps: "Applications Mobiles",
    section_books: "Publications",
    section_music: "Musique",
    section_art: "Studio d'Art",
    section_youtube: "Regarder sur YouTube",
    section_youtube_sub: "Contenu exclusif, présentations de produits et aperçus créateurs sur la chaîne YouTube Elevate360.",
    section_compare: "Comparer Nos Livres",
    section_compare_sub: "Trouvez le bon livre pour votre parcours — bien-être, amour ou vie saine.",
    footer_tagline: "Élever le monde, un produit à la fois.",
    cta_view_channel: "Voir la Chaîne Complète",
    cta_buy_amazon: "Acheter sur Amazon",
    cta_open_app: "Ouvrir l'Application",
    cta_visit_etsy: "Visiter le Studio d'Art",
    cta_subscribe: "S'abonner — C'est Gratuit",
    press_kit: "Dossier de Presse",
  },
  es: {
    nav_apps: "Aplicaciones",
    nav_books: "Libros",
    nav_music: "Música",
    nav_art: "Arte",
    nav_blog: "Blog",
    nav_contact: "Contáctanos",
    hero_badge: "Portafolio de Marca Oficial",
    hero_headline_1: "Eleva Tu Mundo",
    hero_headline_2: "con Elevate360",
    hero_sub: "Aplicaciones · Libros · Música · Arte — una marca, impacto infinito.",
    hero_cta_primary: "Explorar Productos",
    hero_cta_secondary: "Contáctanos",
    section_apps: "Aplicaciones Móviles",
    section_books: "Publicaciones",
    section_music: "Música",
    section_art: "Estudio de Arte",
    section_youtube: "Ver en YouTube",
    section_youtube_sub: "Contenido exclusivo, presentaciones de productos e ideas creativas en el canal de YouTube Elevate360.",
    section_compare: "Comparar Nuestros Libros",
    section_compare_sub: "Encuentra el libro adecuado para tu camino — bienestar, amor o vida saludable.",
    footer_tagline: "Elevar el mundo, un producto a la vez.",
    cta_view_channel: "Ver Canal Completo",
    cta_buy_amazon: "Comprar en Amazon",
    cta_open_app: "Abrir Aplicación",
    cta_visit_etsy: "Visitar Estudio de Arte",
    cta_subscribe: "Suscribirse — Es Gratis",
    press_kit: "Kit de Prensa",
  },
  pt: {
    nav_apps: "Aplicativos",
    nav_books: "Livros",
    nav_music: "Música",
    nav_art: "Arte",
    nav_blog: "Blog",
    nav_contact: "Entre em Contato",
    hero_badge: "Portfólio de Marca Oficial",
    hero_headline_1: "Eleve Seu Mundo",
    hero_headline_2: "com Elevate360",
    hero_sub: "Aplicativos · Livros · Música · Arte — uma marca, impacto infinito.",
    hero_cta_primary: "Explorar Produtos",
    hero_cta_secondary: "Entre em Contato",
    section_apps: "Aplicativos Móveis",
    section_books: "Publicações",
    section_music: "Música",
    section_art: "Estúdio de Arte",
    section_youtube: "Assistir no YouTube",
    section_youtube_sub: "Conteúdo exclusivo, apresentações de produtos e insights criadores no canal do YouTube Elevate360.",
    section_compare: "Comparar Nossos Livros",
    section_compare_sub: "Encontre o livro certo para sua jornada — saúde, amor ou vida saudável.",
    footer_tagline: "Elevar o mundo, um produto de cada vez.",
    cta_view_channel: "Ver Canal Completo",
    cta_buy_amazon: "Comprar na Amazon",
    cta_open_app: "Abrir Aplicativo",
    cta_visit_etsy: "Visitar Estúdio de Arte",
    cta_subscribe: "Inscrever-se — É Grátis",
    press_kit: "Kit de Imprensa",
  },
  zh: {
    nav_apps: "应用程序",
    nav_books: "书籍",
    nav_music: "音乐",
    nav_art: "艺术",
    nav_blog: "博客",
    nav_contact: "联系我们",
    hero_badge: "官方品牌组合",
    hero_headline_1: "提升您的世界",
    hero_headline_2: "与 Elevate360",
    hero_sub: "应用 · 书籍 · 音乐 · 艺术 — 一个品牌，无限影响。",
    hero_cta_primary: "探索产品",
    hero_cta_secondary: "联系我们",
    section_apps: "移动应用程序",
    section_books: "出版物",
    section_music: "音乐",
    section_art: "艺术工作室",
    section_youtube: "在 YouTube 上观看",
    section_youtube_sub: "在 Elevate360 YouTube 频道上欣赏独家内容、产品展示和创作者见解。",
    section_compare: "比较我们的书籍",
    section_compare_sub: "找到适合您旅程的书籍 — 健康、爱情或健康生活。",
    footer_tagline: "提升世界，一次一个产品。",
    cta_view_channel: "查看完整频道",
    cta_buy_amazon: "在亚马逊购买",
    cta_open_app: "打开应用",
    cta_visit_etsy: "访问艺术工作室",
    cta_subscribe: "订阅 — 免费",
    press_kit: "新闻资料袋",
  },
  ja: {
    nav_apps: "アプリ",
    nav_books: "書籍",
    nav_music: "音楽",
    nav_art: "アート",
    nav_blog: "ブログ",
    nav_contact: "お問い合わせ",
    hero_badge: "公式ブランドポートフォリオ",
    hero_headline_1: "あなたの世界を高めよう",
    hero_headline_2: "Elevate360 とともに",
    hero_sub: "アプリ · 書籍 · 音楽 · アート — ひとつのブランド、無限の可能性。",
    hero_cta_primary: "製品を探る",
    hero_cta_secondary: "お問い合わせ",
    section_apps: "モバイルアプリ",
    section_books: "出版物",
    section_music: "音楽",
    section_art: "アートスタジオ",
    section_youtube: "YouTube で見る",
    section_youtube_sub: "Elevate360 YouTube チャンネルで独占コンテンツ、製品紹介、クリエイターの洞察をお楽しみください。",
    section_compare: "書籍を比較する",
    section_compare_sub: "あなたの旅に合った本を見つけよう — ウェルネス、愛、または健康的な生活。",
    footer_tagline: "世界を高める、一製品ずつ。",
    cta_view_channel: "チャンネル全体を見る",
    cta_buy_amazon: "Amazon で購入",
    cta_open_app: "アプリを開く",
    cta_visit_etsy: "アートスタジオを訪問",
    cta_subscribe: "無料で登録",
    press_kit: "プレスキット",
  },
  ru: {
    nav_apps: "Приложения",
    nav_books: "Книги",
    nav_music: "Музыка",
    nav_art: "Искусство",
    nav_blog: "Блог",
    nav_contact: "Связаться",
    hero_badge: "Официальное Портфолио Бренда",
    hero_headline_1: "Подними свой мир",
    hero_headline_2: "с Elevate360",
    hero_sub: "Приложения · Книги · Музыка · Искусство — один бренд, бесконечное влияние.",
    hero_cta_primary: "Изучить продукты",
    hero_cta_secondary: "Связаться",
    section_apps: "Мобильные приложения",
    section_books: "Публикации",
    section_music: "Музыка",
    section_art: "Арт-студия",
    section_youtube: "Смотреть на YouTube",
    section_youtube_sub: "Эксклюзивный контент, презентации продуктов и идеи создателей на YouTube-канале Elevate360.",
    section_compare: "Сравнить наши книги",
    section_compare_sub: "Найдите подходящую книгу для вашего пути — здоровье, любовь или здоровый образ жизни.",
    footer_tagline: "Поднимать мир, один продукт за раз.",
    cta_view_channel: "Смотреть весь канал",
    cta_buy_amazon: "Купить на Amazon",
    cta_open_app: "Открыть приложение",
    cta_visit_etsy: "Посетить арт-студию",
    cta_subscribe: "Подписаться — Бесплатно",
    press_kit: "Пресс-кит",
  },
  yo: {
    nav_apps: "Àpèsè",
    nav_books: "Ìwé",
    nav_music: "Orin",
    nav_art: "Ọnà",
    nav_blog: "Àpèjọ",
    nav_contact: "Kàn sí wa",
    hero_badge: "Àpèsè Àmì Ìdánimọ̀",
    hero_headline_1: "Gbé Ayé Rẹ Sókè",
    hero_headline_2: "pẹ̀lú Elevate360",
    hero_sub: "Àpèsè · Ìwé · Orin · Ọnà — ìdílé kan, ipa àìlópin.",
    hero_cta_primary: "Wo Àwọn Ọjà",
    hero_cta_secondary: "Kàn sí wa",
    section_apps: "Àwọn Àpèsè Alagbeka",
    section_books: "Àwọn Ìwé",
    section_music: "Orin",
    section_art: "Ilé Ọnà",
    section_youtube: "Wo lórí YouTube",
    section_youtube_sub: "Àkóónú àkànṣe, àfihàn ọjà, àti ìmọ̀ olùdásílẹ̀ lórí ìkanni YouTube Elevate360.",
    section_compare: "Ṣe Àfiwé Àwọn Ìwé Wa",
    section_compare_sub: "Wá ìwé tó yẹ fún ìrìnàjò rẹ — ìlera, ìfẹ́, tàbí ìgbé ayé àláfíà.",
    footer_tagline: "Gbé ayé sókè, ọjà kan lẹ́yìn ọjà.",
    cta_view_channel: "Wo Ìkanni Pípé",
    cta_buy_amazon: "Ra ní Amazon",
    cta_open_app: "Ṣí Àpèsè",
    cta_visit_etsy: "Ṣèbẹ̀wò Ilé Ọnà",
    cta_subscribe: "Forúkọsílẹ̀ — Ọ̀fẹ́",
    press_kit: "Ìwé Ìgbohunsafẹ́fẹ́",
  },
} as const;

export type TranslationKey = keyof (typeof translations)["en"];

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => translations.en[key],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>(() => {
    return (localStorage.getItem("e360_lang") as Language) ?? "en";
  });

  const handleSetLang = (l: Language) => {
    setLang(l);
    localStorage.setItem("e360_lang", l);
  };

  const t = (key: TranslationKey): string =>
    (translations[lang] as Record<string, string>)[key] ?? translations.en[key];

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
